### ISSUE TITLE
`pingone_licenses` panic when using `data_filter`

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-pingone#182]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version

v0.6.0

### Terraform Version

N/a

### Affected Resource(s)

- pingone_licenses

### Terraform Configuration Files
```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue

data "pingone_licenses" "license" {

  organization_id = data.pingone_environment.admins_org.organization_id

  data_filter {
    name   = "package"
    values = ["INTERNAL"]
  }

  data_filter {
    name   = "status"
    values = ["ACTIVE"]
  }
}

```

### Panic Output

```
Stack trace from the terraform-provider-pingone_v0.6.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1979609]

goroutine 22 [running]:
github.com/pingidentity/terraform-provider-pingone/internal/sdk.ParseResponseWithCustomTimeout({0x1de04c0, 0xc0000f54a0}, 0x1c1a880?, {0x1c682cc, 0xf}, 0x28?, 0x1bb5000?, 0xc00041a201?)
        github.com/pingidentity/terraform-provider-pingone/internal/sdk/sdk.go:88 +0x389
github.com/pingidentity/terraform-provider-pingone/internal/sdk.ParseResponse({0x1de04c0?, 0xc0000f54a0?}, 0x1af6c20?, {0x1c682cc?, 0x1b1e0a0?}, 0xc0000f5470?, 0x1273638?)
        github.com/pingidentity/terraform-provider-pingone/internal/sdk/sdk.go:56 +0x32
github.com/pingidentity/terraform-provider-pingone/internal/service/base.datasourcePingOneLicensesRead({0x1de0488, 0xc0000965a0}, 0xc0000e4380, {0x1a88a60?, 0xc000795c30})
        github.com/pingidentity/terraform-provider-pingone/internal/service/base/data_source_licenses.go:99 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000255b20, {0x1de04c0, 0xc0002cb920}, 0xd?, {0x1a88a60, 0xc000795c30})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000255b20, {0x1de04c0, 0xc0002cb920}, 0xc0000e4280, {0x1a88a60, 0xc000795c30})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0003fe4f8, {0x1de04c0?, 0xc0002cb7d0?}, 0xc000150260)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.23.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0003e3540, {0x1de04c0?, 0xc0002ca540?}, 0xc0000d40a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1c1a720?, 0xc0003e3540}, {0x1de04c0, 0xc0002ca540}, 0xc0000e0000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e61e0, {0x1de3d00, 0xc00048a1a0}, 0xc0000da000, 0xc000431b30, 0x24870f0, 0x0)
        google.golang.org/grpc@v1.49.0/server.go:1301 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0001e61e0, {0x1de3d00, 0xc00048a1a0}, 0xc0000da000, 0x0)
        google.golang.org/grpc@v1.49.0/server.go:1642 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.49.0/server.go:938 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.49.0/server.go:936 +0x28a

Error: The terraform-provider-pingone_v0.6.0 plugin crashed!
```

### Expected Behavior

Friendly error returned

### Actual Behavior

Panic crash

### Steps to Reproduce

1. `terraform apply`

**Comment by patrickcping** [comment]
Issue occurs when the organisation contains an expired license which either has the `package` value of `MFA TRIAL` or `RISKTRIAL`.

The SDK needs to handle the error better, and add support for the missing package values

**Comment by patrickcping** [comment]
The SDK now handles the error better as of `v0.6.1`, but the full list of license package codes is yet to be included

**Comment by patrickcping** [comment]
The `package` field should be made free-text and not restricted to specific values.  The package names can change over time.
