### ISSUE TITLE
Provider crash when MFA Sign On Policy Action is created using the provider and then modified in the admin console

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-pingone#226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### PingOne Terraform provider Version

v0.7.0

### Terraform Version

Terraform v1.3.6
on darwin_amd64

### Affected Resource(s)

- pingone_sign_on_policy_action

### Terraform Configuration Files
```hcl
# Copy-paste your PingOne related Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Remember to replace any account/customer sensitive information in the configuration before submitting the issue
resource "pingone_sign_on_policy_action" "my_policy_mfa" {
  environment_id    = pingone_environment.my_environment.id
  sign_on_policy_id = pingone_sign_on_policy.my_policy.id

  priority = 2

  conditions {
    last_sign_on_older_than_seconds = 86400 // 24 hours

    ip_reputation_high_risk = true
    geovelocity_anomaly_detected = true
    anonymous_network_detected = true

  }

  mfa {
    device_sign_on_policy_id = ""
  }

}
```

### Debug Output

N/a - note stack trace below

### Panic Output

```
Stack trace from the terraform-provider-pingone_v0.7.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19f6fc6]

goroutine 372 [running]:
github.com/pingidentity/terraform-provider-pingone/internal/service/sso.flattenConditions({0x0, 0x0, 0x0, 0xc000674a98})
        github.com/pingidentity/terraform-provider-pingone/internal/service/sso/resource_sign_on_policy_action.go:1426 +0x3c6
github.com/pingidentity/terraform-provider-pingone/internal/service/sso.resourceSignOnPolicyActionRead({0x1e21ce8, 0xc0003016e0}, 0xc0003de380, {0x1abb800?, 0xc000388b50})
        github.com/pingidentity/terraform-provider-pingone/internal/service/sso/resource_sign_on_policy_action.go:259 +0xaaa
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004dfb20, {0x1e21d20, 0xc0001cb110}, 0xd?, {0x1abb800, 0xc000388b50})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004dfb20, {0x1e21d20, 0xc0001cb110}, 0xc000923040, {0x1abb800, 0xc000388b50})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000d920, {0x1e21d20?, 0xc0001caff0?}, 0xc00022b580)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x497
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00045f900, {0x1e21d20?, 0xc0001ca930?}, 0xc000301140)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x49e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1c523e0?, 0xc00045f900}, {0x1e21d20, 0xc0001ca930}, 0xc000445340, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x1e255e0, 0xc0003161a0}, 0xc00061ad80, 0xc0004f0ba0, 0x24e33b0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x1e255e0, 0xc0003161a0}, 0xc00061ad80, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-pingone_v0.7.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
### Expected Behavior

Terraform plan should not fail, and show configuration drift from changes in the admin console

### Actual Behavior

Provider/Plugin crash error

### Steps to Reproduce

1. `terraform apply` of included HCL
2. In the PingOne console, manual change to the MFA sign on policy action (disable `ip_reputation_high_risk` condition) and save
3. `terraform plan` or `terraform apply`

### References

- #216

**Comment by patrickcping** [comment]
The issue occurs because the console re-writes the condition for `last_sign_on_older_than_seconds` to an MFA specific condition which the provider cannot interpret.  Secondary issue is a failed error catch.

Fixed in upcoming release:
* Error catch issue resolved
* New condition added `last_sign_on_older_than_seconds_mfa` to distinguish between a general last sign on activity and last sign on using an MFA device
